# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau22-recept-grupp3-j35j900nj4w3.reky.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Toast skagen",
    "description": "Gott till champagne",
    "ratings": [],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_67954/cf_259/toast_skagen_med_hemmagjord_majonnas.jpg",
    "timeInMins": 20,
    "categories": [ "Förrätt", "Skaldjur", "Frukost", "Lunch", "Middag" ],
    "instructions": [ "Stek brödet", "Lägg på röran", "Toppa med Dill"],
    "ingredients": [
        {
            "name": "Räkor",
            "amount": 500,
            "unit": "gram"
        },
        {
            "name": "Dill",
            "amount": 1,
            "unit": "kruka"
        },
        {
            "name": "Majonäs",
            "amount": 1.5,
            "unit": "deciliter"
        },
        {
            "name": "Citron",
            "amount": 1,
            "unit": "hel"
        },
        {
            "name": "Salt",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Peppar",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Bröd",
            "amount": 2,
            "unit": "skivor"
        },
        {
            "name": "Löjrom",
            "amount": 80,
            "unit": "gram"
        }
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Tacos",
    "description": "Fredagsmys",
    "ratings": [4, 5, 4, 4, 5, 4],
    "imageUrl": "https://res.cloudinary.com/anora/image/upload/t_OgImage-MD-MD/f_auto/folkofolk%2Ftacos-texmex",
    "timeInMins": 30,
    "categories": [ "Lunch", "Middag" ],
    "instructions": [ "Sätt på ugnen", "Hacka grönsaker", "Stek färsen"],
    "ingredients": [
        {
            "name": "Tomat",
            "amount": 2,
            "unit": "stycken"
        },
        {
            "name": "Gurka",
            "amount": 1,
            "unit": "stycken"
        },
        {
            "name": "Lök",
            "amount": 1,
            "unit": "stycken"
        },
        {
            "name": "Majskorn",
            "amount": 1,
            "unit": "burk"
        },
        {
            "name": "Isbergssallad",
            "amount": 1.25,
            "unit": "stycken"
        },
        {
            "name": "Nötfärs",
            "amount": 500,
            "unit": "gram"
        },
        {
            "name": "Olja",
            "amount": 2,
            "unit": "msk"
        },
        {
            "name": "Tacokrydda",
            "amount": 1,
            "unit": "påse"
        },
        {
            "name": "Vatten",
            "amount": 1.5,
            "unit": "deciliter"
        },
        {
            "name": "Tacobröd",
            "amount": 4,
            "unit": "stycken"
        },
        {
            "name": "Riven ost",
            "amount": 2,
            "unit": "deciliter"
        },
        {
            "name": "Salsa",
            "amount": 2,
            "unit": "deciliter"
        },
        {
            "name": "Gräddfil",
            "amount": 2,
            "unit": "deciliter"
        }
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Tabbouleh",
    "description": "Passar utmärkt som tillbehör till grillat eller på en buffé",
    "ratings": [3, 5, 3, 4, 5, 2],
    "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flickr_-_cyclonebill_-_Tabbouleh.jpg",
    "timeInMins": 25,
    "categories": [ "Lunch", "Middag", "Sallad"],
    "instructions": [ "Koka bulgur", "Finhacka persilja och lök, tärna tomaterna", "Blanda ingredienserna", "Blanda ingredienserna"],
    "ingredients": [
        {
            "name": "Bulgur",
            "amount": 1,
            "unit": "deciliter"
        },
        {
            "name": "Bladpersilja",
            "amount": 100,
            "unit": "gram"
        },
        {
            "name": "Lök",
            "amount": 1,
            "unit": "stycken"
        },
        {
            "name": "Tomat",
            "amount": 3,
            "unit": "stycken"
        },
        {
            "name": "Citronjuice",
            "amount": 0.75,
            "unit": "deciliter"
        },
        {
            "name": "Olivolja",
            "amount": 1,
            "unit": "deciliter"
        },
        {
            "name": "Salt",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Peppar",
            "amount": 2,
            "unit": "krm"
        }
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Kladdkaka",
    "description": "Snabb, enkel och god",
    "ratings": [3, 4, 5, 4, 3, 5],
    "imageUrl": "https://cdn-rdb.arla.com/Files/arla-se/2806554286/75c9f5fb-375f-41b8-8c89-e7cbfb9c0278.jpg?w=1269&h=715&mode=crop&ak=f525e733&hm=b762ca1a",
    "timeInMins": 30,
    "categories": [ "Efterrät"],
    "instructions": [ "Sätt på ugnen", "Smält smöret", "Rör ner ingredienserna och blanda väl", "Häll smeten i en smord och bröad form", "Grädda i 15 minuter"],
    "ingredients": [
        {
            "name": "Smör",
            "amount": 100,
            "unit": "gram"
        },
        {
            "name": "Strösocker",
            "amount": 225,
            "unit": "gram"
        },
        {
            "name": "Ägg",
            "amount": 2,
            "unit": "stycken"
        },
        {
            "name": "Vetemjöl",
            "amount": 1,
            "unit": "deciliter"
        },
        {
            "name": "Kakao",
            "amount": 3,
            "unit": "msk"
        },
        {
            "name": "Vaniljsocker",
            "amount": 1,
            "unit": "tsk"
        },
        {
            "name": "Vispgrädde",
            "amount": 3,
            "unit": "deciliter"
        }
    ]
}

###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=toas HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/63309a293120fd5bba986857 HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/63309a293120fd5bba986857 HTTP/1.1
Content-Type: application/json

{
  "description": "Gott till apelsinsaft"
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Förrätt/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=toa HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/63309a293120fd5bba986857/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/63309a293120fd5bba986857/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/63309a293120fd5bba986857/comments
Content-Type: application/json

{
    "comment": "För mycket salt!",
    "name": "Bosse"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
